# Generated by Django 4.2.24 on 2025-09-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_app', '0002_rename_is_completed_assignment_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='completed',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='event_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_date',
            field=models.DateTimeField(),
        ),
    ]
