# Generated by Django 4.2.24 on 2025-09-15 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic_app', '0004_auto_20250915_2212'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_course_date',
        ),
        migrations.RemoveConstraint(
            model_name='course',
            name='unique_user_course_code',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(help_text='Due date and time'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='description',
            field=models.TextField(blank=True, help_text='Event description', null=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='event_date',
            field=models.DateTimeField(help_text='Event date and time'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, help_text="Course code (e.g., 'MATH301')", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.CharField(blank=True, help_text='Instructor name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_date',
            field=models.DateTimeField(help_text='Exam date and time'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('course', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('user', 'code')},
        ),
    ]
